#! /bin/bash

IMAGE_VERSION=0.12
CONTAINER_VOLUMES_DIR=${HOME}/docker_volumes/imapscan

mkdir ${CONTAINER_VOLUMES_DIR}/spamassassin 2>/dev/null
mkdir ${CONTAINER_VOLUMES_DIR}/accounts 2>/dev/null
mkdir ${CONTAINER_VOLUMES_DIR}/imapfilter 2>/dev/null

docker run -d --name imapscan_${IMAGE_VERSION} \
	-v ${CONTAINER_VOLUMES_DIR}/spamassassin:/var/spamassassin \
	-v ${CONTAINER_VOLUMES_DIR}/imapfilter:/root/.imapfilter \
	-v ${CONTAINER_VOLUMES_DIR}/accounts:/root/accounts \
	domcomte/imapscan-rpi2:latest
