#! /bin/bash

cd /root
if [ ! -f startup_done ]; then
  # move default config files to volumes if missing
  if [ ! -f /var/spamassassin/user_prefs ]; then
    mv spamassassin_user_prefs /var/spamassassin/user_prefs
  else
    rm spamassassin_user_prefs
  fi
  if [ ! -f .imapfilter/config.lua ]; then
    mv imapfilter_config.lua .imapfilter/config.lua
  else
    rm imapfilter_config.lua
  fi
  if [ ! -f accounts/imap_accounts.txt ]; then
    cp imap_accounts.txt accounts/imap_accounts.txt
    mv imap_accounts.txt accounts/imap_accounts_learn.txt
  else
    rm imap_accounts.txt
  fi

  # move configuration files in place
  mv rsyslog.conf /etc/

  # start services, etc...
  service rsyslog start

  logger "running sa-learn"
  sa-learn --force-expire -D

  logger "starting spamassassin"
  service spamassassin start

  if [ ! -f /var/spamassassin/initial_learn_done ]; then
    logger "running initial learm_spam script"
    ./learn_spam.sh
    touch /var/spamassassin/initial_learn_done
  fi

  logger "starting CRON"
  service cron start

  touch startup_done
fi
